image: docker:20

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add jq
  - export DEPLOY_HOST=$(echo $DEPLOY_CONFIG_CLOUD | jq -r '.host')
  - mkdir -p ~/.docker
  - echo $DEPLOY_CONFIG_CLOUD | jq -r '.ca' > ~/.docker/ca.pem
  - echo $DEPLOY_CONFIG_CLOUD | jq -r '.client_cert' > ~/.docker/cert.pem
  - echo $DEPLOY_CONFIG_CLOUD | jq -r '.client_key' > ~/.docker/key.pem
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

Build:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --platform=linux/amd64 --pull --cache-from $CI_REGISTRY_IMAGE:latest --push --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .

deploy:
  stage: deploy
  script:
    - export "DOCKER_HOST=tcp://$DEPLOY_HOST:2376" DOCKER_TLS_VERIFY=1
    - docker-compose pull
    - docker-compose up -d
  environment:
    name: production

