version: '2.2'
services:
  app:
    restart: always
    image: ghcr.io/akiba-hs/auth-service:${COMMIT_SHA}
    labels:
      - "traefik.http.routers.auth.rule=HostRegexp(`auth.akiba.space`)"
      - "traefik.enable=true"
    environment:
     - BOT_TOKEN=$BOT_TOKEN
     - CHAT_ID=$CHAT_ID
     - JWT_KEY=$JWT_KEY
     - UNLOCK_URL=$UNLOCK_URL
