name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/auth-service
          BRANCH_NAME=${{ github.ref_name }}
          TAG=${BRANCH_NAME//\//-}  # Меняем слэши на дефисы

          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
        